import type {
  Agent,
  AiDebugRun,
  Conversation,
  EventLogItem,
  InboxManager,
  KnowledgeItem,
  Lead,
  MailerCampaign,
  MailerDomain,
  Metric,
  ReviewItem,
  TrainingExample,
} from "../types";

export const mailerDomains: MailerDomain[] = [
  {
    id: 1,
    domain: "askkinvestowl.com",
    registrar: "Cloudflare",
    spfStatus: "Verified",
    dkimStatus: "Verified",
    dmarcStatus: "Verified",
    mxStatus: "Verified",
    status: "Active",
    configurationSetStatus: "Configured",
    mailboxes: [
      {
        id: 1, email: "sarah.connor@askkinvestowl.com", status: "Active", warmupStage: "Ramping", warmupEnabled: true,
        dailyLimit: 20, sentToday: 2, warmupDailyLimit: 20, warmupSentToday: 20, totalEmailsSent: 214,
        warmupDeliverability7d: 90.2, replyRate7d: 0, bounceRate3d: 0,
        campaignName: "Q3 Investor Outreach", reputationStatus: "Healthy", lastSentAt: "2026-09-04T09:12:00Z",
      },
      {
        id: 2, email: "s.connor@askkinvestowl.com", status: "Active", warmupStage: "Ramping", warmupEnabled: true,
        dailyLimit: 20, sentToday: 2, warmupDailyLimit: 20, warmupSentToday: 20, totalEmailsSent: 187,
        warmupDeliverability7d: 83.2, replyRate7d: 0, bounceRate3d: null,
        campaignName: "Q3 Investor Outreach", reputationStatus: "Healthy", lastSentAt: "2026-09-04T08:40:00Z",
      },
      {
        id: 3, email: "sarah.c@askkinvestowl.com", status: "Active", warmupStage: "Ramping", warmupEnabled: true,
        dailyLimit: 20, sentToday: 2, warmupDailyLimit: 20, warmupSentToday: 20, totalEmailsSent: 176,
        warmupDeliverability7d: 85.5, replyRate7d: 0, bounceRate3d: null,
        campaignName: "Q3 Investor Outreach", reputationStatus: "Healthy", lastSentAt: "2026-09-04T07:55:00Z",
      },
      {
        id: 4, email: "sarah.connor2@askkinvestowl.com", status: "Active", warmupStage: "Ramping", warmupEnabled: true,
        dailyLimit: 20, sentToday: 2, warmupDailyLimit: 20, warmupSentToday: 20, totalEmailsSent: 162,
        warmupDeliverability7d: 80.6, replyRate7d: 7.1, bounceRate3d: null,
        campaignName: "Q3 Investor Outreach", reputationStatus: "Watch", lastSentAt: "2026-09-04T07:10:00Z",
      },
      {
        id: 5, email: "sarah@askkinvestowl.com", status: "Active", warmupStage: "New", warmupEnabled: true,
        dailyLimit: 20, sentToday: 4, warmupDailyLimit: 20, warmupSentToday: 20, totalEmailsSent: 9,
        warmupDeliverability7d: 83.8, replyRate7d: 0, bounceRate3d: null,
        campaignName: null, reputationStatus: "Healthy", lastSentAt: "2026-09-04T06:20:00Z",
      },
    ],
  },
];

export const mailerCampaigns: MailerCampaign[] = [
  {
    id: 1,
    name: "Q3 Investor Outreach",
    status: "Active",
    mailboxCount: 4,
    sentToday: 8,
    sentTotal: 739,
    replyRate: 2.1,
    bounceRate: 1.4,
    startedAt: "2026-08-18T00:00:00Z",
    leadsCount: 480,
    contactedCount: 214,
    contactedPercent: 44.6,
    replyCount: 16,
    positiveReplyRate: null,
    openTrackingSupported: false,
    totalSequenceEmails: 960,
  },
];

export const metrics: Metric[] = [
  { label: "Active AI Agents", value: "8", change: "+2", tone: "success" },
  { label: "Conversations Today", value: "142", change: "+18.4%", tone: "success" },
  { label: "AI Replies Sent", value: "96", change: "+12.1%", tone: "success" },
  { label: "Human Review Required", value: "17", change: "-3.2%", tone: "warning" },
  { label: "Positive Replies", value: "41", change: "+7.8%", tone: "success" },
  { label: "Meetings Generated", value: "12", change: "+4", tone: "accent" },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    lead: "Sarah Mitchell",
    company: "Acme Technologies",
    role: "VP Growth",
    email: "sarah@acmetech.example",
    latestMessage: "Interesting. What exactly do you guys do for outbound replies?",
    intent: "Question",
    agent: "Outbound Sales Agent",
    status: "AI draft ready",
    updated: "4 min",
    sentiment: "Positive",
    stage: "Discovery",
    interest: "High",
    confidence: 96,
    recommendation: "Answer the product question directly and offer a short discovery call.",
    messages: [
      {
        from: "human",
        sender: "Kate Moore",
        time: "9:14 AM",
        body: "Hi Sarah, noticed Acme has been expanding its outbound team. ReplyOS helps teams respond to interested prospects faster without losing control of the message.",
      },
      {
        from: "prospect",
        sender: "Sarah Mitchell",
        time: "9:22 AM",
        body: "Interesting. What exactly do you guys do for outbound replies?",
      },
      {
        from: "ai",
        sender: "Alex - Sales Assistant",
        time: "Draft",
        body: "We connect to PlusVibe, read prospect replies, classify intent, and generate a sales-ready response using your company context and rules. If confidence is high it can send automatically; otherwise it routes the reply to your team for review. Would it be useful to see how that works against one of Acme's current campaigns?",
      },
    ],
  },
  {
    id: "conv-2",
    lead: "Daniel Cho",
    company: "Northstar Cloud",
    role: "Revenue Operations",
    email: "daniel@northstar.example",
    latestMessage: "Can you send pricing before we set up a call?",
    intent: "Question",
    agent: "Enterprise Agent",
    status: "Needs review",
    updated: "16 min",
    sentiment: "Neutral",
    stage: "Evaluation",
    interest: "Medium",
    confidence: 87,
    recommendation: "Answer at a high level, avoid discount claims, and route pricing negotiation to human review.",
    messages: [
      {
        from: "prospect",
        sender: "Daniel Cho",
        time: "8:48 AM",
        body: "Can you send pricing before we set up a call?",
      },
    ],
  },
  {
    id: "conv-3",
    lead: "Priya Raman",
    company: "Vector Labs",
    role: "Head of Sales",
    email: "priya@vector.example",
    latestMessage: "We already have an agency handling this.",
    intent: "Objection",
    agent: "Outbound Sales Agent",
    status: "AI sent",
    updated: "31 min",
    sentiment: "Skeptical",
    stage: "Objection",
    interest: "Medium",
    confidence: 94,
    recommendation: "Acknowledge the agency and position ReplyOS as response operations, not a replacement.",
    messages: [
      {
        from: "prospect",
        sender: "Priya Raman",
        time: "8:19 AM",
        body: "We already have an agency handling this.",
      },
    ],
  },
  {
    id: "conv-4",
    lead: "Marcus Lee",
    company: "Orbit Finance",
    role: "Founder",
    email: "marcus@orbit.example",
    latestMessage: "Sure, Thursday morning works. Send me the invite.",
    intent: "Meeting Request",
    agent: "Demo Agent",
    status: "Human managed",
    updated: "52 min",
    sentiment: "Positive",
    stage: "Meeting",
    interest: "Very high",
    confidence: 98,
    recommendation: "Confirm the meeting and hand off calendar coordination.",
    messages: [
      {
        from: "prospect",
        sender: "Marcus Lee",
        time: "7:58 AM",
        body: "Sure, Thursday morning works. Send me the invite.",
      },
    ],
  },
];

export const inboxManagers: InboxManager[] = [
  {
    name: "Inbox Manager 01",
    workspace: "PLWH Sales",
    status: "Active",
    agent: "Outbound Sales Agent",
    autoReply: true,
    repliesToday: 34,
    humanReview: 5,
  },
  {
    name: "Enterprise Reply Queue",
    workspace: "PLWH Enterprise",
    status: "Active",
    agent: "Enterprise Agent",
    autoReply: true,
    repliesToday: 18,
    humanReview: 7,
  },
  {
    name: "Demo Follow-up Inbox",
    workspace: "PLWH Demos",
    status: "Paused",
    agent: "Demo Agent",
    autoReply: false,
    repliesToday: 9,
    humanReview: 9,
  },
];

export const agents: Agent[] = [
  {
    name: "Outbound Sales Agent",
    purpose: "Initial replies, qualification, objections",
    model: "GPT",
    status: "Active",
    inbox: "PLWH Sales",
    autoReply: true,
    updated: "Today, 9:31 AM",
  },
  {
    name: "Enterprise Agent",
    purpose: "Complex B2B questions and pricing guardrails",
    model: "GPT",
    status: "Active",
    inbox: "PLWH Enterprise",
    autoReply: true,
    updated: "Yesterday, 4:12 PM",
  },
  {
    name: "Demo Agent",
    purpose: "Meeting requests and post-demo follow-up",
    model: "GPT",
    status: "Paused",
    inbox: "PLWH Demos",
    autoReply: false,
    updated: "Aug 27, 2026",
  },
];

export const knowledgeItems: KnowledgeItem[] = [
  { id: 1, title: "Pricing FAQ", category: "Sales FAQs", sourceType: "FAQ", owner: "Revenue Ops", status: "Published", chunks: 3, agents: [], updated: "2h ago" },
  { id: 2, title: "Agency objection handling", category: "Objection Handling", sourceType: "Text", owner: "Sales Enablement", status: "Published", chunks: 2, agents: [], updated: "Yesterday" },
  { id: 3, title: "PlusVibe integration overview", category: "Product Details", sourceType: "Document", owner: "Product", status: "Review", chunks: 0, agents: [], updated: "Aug 28" },
  { id: 4, title: "Claims the AI must never make", category: "Policies", sourceType: "Text", owner: "Compliance", status: "Published", chunks: 2, agents: [], updated: "Aug 25" },
];

export const reviewQueue: ReviewItem[] = [
  {
    id: "review-1",
    lead: "Daniel Cho",
    company: "Northstar Cloud",
    trigger: "Pricing question requires approval",
    confidence: 87,
    status: "Needs Review",
    agent: "Enterprise Agent",
    age: "16 min",
    draft: "Happy to share a range, but exact pricing depends on reply volume and approval controls. Worth a quick call so I can point you to the right tier?",
  },
  {
    id: "review-2",
    lead: "Alicia Gomez",
    company: "Brightpath Health",
    trigger: "Sensitive compliance language detected",
    confidence: 82,
    status: "Needs Review",
    agent: "Outbound Sales Agent",
    age: "28 min",
    draft: "I can clarify how ReplyOS supports controlled review workflows, but I do not want to overstate compliance coverage without your requirements.",
  },
  {
    id: "review-3",
    lead: "Owen Mercer",
    company: "Trailhead Apps",
    trigger: "Prospect asked for contract terms",
    confidence: 79,
    status: "Paused",
    agent: "Demo Agent",
    age: "44 min",
    draft: "I can connect you with our team for contract specifics. Would tomorrow afternoon work for a quick handoff?",
  },
];

export const leads: Lead[] = [
  {
    name: "Sarah Mitchell",
    email: "sarah@acmetech.example",
    company: "Acme Technologies",
    role: "VP Growth",
    campaign: "Outbound AI Reply Ops",
    intent: "Question",
    sentiment: "Positive",
    stage: "Discovery",
    owner: "Kate Moore",
    updated: "4 min ago",
  },
  {
    name: "Daniel Cho",
    email: "daniel@northstar.example",
    company: "Northstar Cloud",
    role: "Revenue Operations",
    campaign: "Enterprise Reply Automation",
    intent: "Question",
    sentiment: "Neutral",
    stage: "Evaluation",
    owner: "Kate Moore",
    updated: "16 min ago",
  },
  {
    name: "Priya Raman",
    email: "priya@vector.example",
    company: "Vector Labs",
    role: "Head of Sales",
    campaign: "Agency Objection Sequence",
    intent: "Objection",
    sentiment: "Skeptical",
    stage: "Objection",
    owner: "Alex Agent",
    updated: "31 min ago",
  },
  {
    name: "Marcus Lee",
    email: "marcus@orbit.example",
    company: "Orbit Finance",
    role: "Founder",
    campaign: "Founder Follow-up",
    intent: "Meeting Request",
    sentiment: "Positive",
    stage: "Meeting",
    owner: "Human Managed",
    updated: "52 min ago",
  },
];

export const trainingExamples: TrainingExample[] = [
  {
    id: "train-1",
    prospectMessage: "We already have an agency handling this.",
    humanResponse: "Totally understand. We usually help teams keep agency-generated pipeline moving by responding to interested replies faster.",
    intent: "Existing solution objection",
    outcome: "Positive reply",
    quality: "High",
    meetingBooked: false,
    included: true,
    updated: "Yesterday",
  },
  {
    id: "train-2",
    prospectMessage: "Can you send pricing before we set up a call?",
    humanResponse: "I can share the general range, but the useful number depends on reply volume and how much approval control you need.",
    intent: "Pricing question",
    outcome: "Meeting booked",
    quality: "High",
    meetingBooked: true,
    included: true,
    updated: "2 days ago",
  },
  {
    id: "train-3",
    prospectMessage: "Not interested right now.",
    humanResponse: "No problem. I will close the loop here. If reply volume becomes painful later, happy to be a resource.",
    intent: "Not interested",
    outcome: "Closed respectfully",
    quality: "Medium",
    meetingBooked: false,
    included: true,
    updated: "Aug 25",
  },
];

export const eventLogs: EventLogItem[] = [
  { timestamp: "09:22 AM", event: "reply.received", workspace: "PLWH Sales", lead: "Sarah Mitchell", conversation: "conv-1", status: "Success", duration: "312 ms" },
  { timestamp: "09:22 AM", event: "ai.analysis.completed", workspace: "PLWH Sales", lead: "Sarah Mitchell", conversation: "conv-1", status: "Success", duration: "1.8 s" },
  { timestamp: "09:23 AM", event: "ai.response.generated", workspace: "PLWH Sales", lead: "Sarah Mitchell", conversation: "conv-1", status: "Success", duration: "2.1 s" },
  { timestamp: "09:07 AM", event: "human.review.required", workspace: "PLWH Enterprise", lead: "Daniel Cho", conversation: "conv-2", status: "Processing", duration: "842 ms" },
  { timestamp: "08:31 AM", event: "plusvibe.request.failed", workspace: "PLWH Demos", lead: "Mina Patel", conversation: "conv-9", status: "Failed", duration: "4.6 s", error: "PlusVibe send endpoint returned 429" },
];

export const aiDebugRun: AiDebugRun = {
  conversation: "conv-1",
  lead: "Sarah Mitchell",
  agent: "Outbound Sales Agent",
  model: "Configured OpenAI model",
  confidence: 96,
  automationDecision: "Auto Send",
  sections: [
    { title: "Agent Instructions", value: "Friendly, concise, consultative. Move interested prospects toward a discovery meeting without pressure." },
    { title: "Lead Information", value: "VP Growth at Acme Technologies. Positive sentiment, discovery stage, high interest." },
    { title: "Retrieved Knowledge", value: "PlusVibe integration overview, pricing FAQ, claims the AI must never make." },
    { title: "Intent Analysis", value: "Prospect asked a product capability question about outbound reply automation." },
    { title: "Strategy", value: "Answer directly, explain the control loop, and ask whether a quick workflow review would be useful." },
    { title: "Safety Check", value: "No restricted claims, no invented pricing, no credential exposure, one clear question." },
  ],
};

export const activitySeries = [
  { day: "Mon", incoming: 38, ai: 31, human: 7 },
  { day: "Tue", incoming: 52, ai: 43, human: 9 },
  { day: "Wed", incoming: 44, ai: 35, human: 11 },
  { day: "Thu", incoming: 61, ai: 48, human: 13 },
  { day: "Fri", incoming: 57, ai: 46, human: 10 },
  { day: "Sat", incoming: 33, ai: 24, human: 6 },
  { day: "Sun", incoming: 29, ai: 21, human: 5 },
];
